src/main/java/de/fhg/fokus/odp/harvester/actions/HarvesterController.java
package de.fhg.fokus.odp.harvester.actions;

import de.fhg.fokus.odp.harvester.application.AppLocalization;
import de.fhg.fokus.odp.harvester.persistence.HarvestersManager;
import de.fhg.fokus.odp.harvester.persistence.entities.Harvester;
import de.fhg.fokus.odp.harvester.persistence.entities.Repository;
import de.fhg.fokus.odp.harvester.persistence.enums.Frequency;
import de.fhg.fokus.odp.harvester.persistence.enums.RepositoryType;
import de.fhg.fokus.odp.harvester.rdf.CountriesAuthorityTable;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

import java.io.Serializable;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@Named
@ViewScoped
public class HarvesterController implements Serializable {

	private static final long serialVersionUID = -534693913871978425L;
	
	private String searchTerm = "";
	private boolean errorsOnly = false;

	private final Integer PAGESIZE = 15;

	private Integer offset = 0;

	private int sort = 1;

	@Inject
	private AppLocalization localization;

	@Inject
	private CountriesAuthorityTable mdrCountries;

	@Inject
	private HarvestersManager harvestersManager;

	private List<Harvester> harvesters;

	private List<Frequency> selectedFrequencies = new ArrayList<>();
	private Map<Frequency, Long> frequencyCounters = new HashMap<>();

	private List<RepositoryType> selectedTypes = new ArrayList<>();
	private Map<RepositoryType, Long> typeCounters = new HashMap<>();

	private List<String> selectedCountries = new ArrayList<>();
	private Map<String, Long> countryCounters = new HashMap<>();

	@Transactional
	public void load() {
		fetchlist();
	}

	@Transactional
	public void search() {
		fetchlist();
	}

	private void fetchlist() {
		offset = 0;
		harvesters = harvestersManager.listHarvesters(null, null, searchTerm, errorsOnly);
		frequencyCounters = harvesters.stream().collect(Collectors.groupingBy(Harvester::getFrequency, Collectors.counting()));
		typeCounters = harvesters.stream().map(Harvester::getSource).collect(Collectors.groupingBy(Repository::getRepositoryType, Collectors.counting()));
		countryCounters = harvesters.stream().map(Harvester::getSource).flatMap(r -> r.getSpatial().stream()).collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
	}

	public Integer getOffset() {
		return offset;
	}

	public void setOffset(Integer offset) {
		this.offset = offset < 0 ? 0 : offset;
	}

	public Long getTotal() {
		return getHarvestersStream().count();
	}

	public Long getRows() {
		long size = getTotal();
		return size - PAGESIZE > offset ? PAGESIZE : size - offset;
	}

	public List<Harvester> getAllHarvesters() {
		if (sort == 1 || sort == 2) {
			harvesters.sort(Comparator.comparing(Harvester::getName));
		} else {
			harvesters.sort(Comparator.nullsLast(Comparator.comparing(Harvester::getNextHarvestDate)));
		}
		if (sort == 2 || sort == 4) {
			Collections.reverse(harvesters);
		}
		return harvesters;
	}

	public List<Harvester> getHarvesters() {
		return getHarvestersStream().skip(offset).limit(PAGESIZE).collect(Collectors.toList());
	}

	private Stream<Harvester> getHarvestersStream() {
		Stream<Harvester> stream = harvesters.stream();
		if (!selectedFrequencies.isEmpty()) {
			stream = stream.filter(h -> selectedFrequencies.contains(h.getFrequency()));
		}
		if (!selectedTypes.isEmpty()) {
			stream = stream.filter(h -> selectedTypes.contains(h.getSource().getRepositoryType()));
		}
		if (!selectedCountries.isEmpty()) {
			stream = stream.filter(h -> h.getSource().getSpatial().stream().map(s -> mdrCountries.prefLabel(s, localization.getLocaleCode())).anyMatch(selectedCountries::contains));
		}
		return stream;
	}

	public Frequency[] getFrequencies() {
		return Frequency.values();
	}

	public RepositoryType[] getRepositoryTypes() {
		return RepositoryType.values();
	}

	public String[] getCountries() {
		return mdrCountries.getEurope(localization.getLocaleCode()).keySet().toArray(new String[] {});
	}

	public String getSearchTerm() {
		return searchTerm;
	}
	
	public void setSearchTerm(String searchTerm) {
		this.searchTerm = searchTerm;
	}

	public boolean isErrorsOnly() {
		return errorsOnly;
	}

	public void setErrorsOnly(boolean errorsOnly) {
		this.errorsOnly = errorsOnly;
	}

	@Transactional
	public void nextPage() {
		offset += PAGESIZE;
	}

	@Transactional
	public void previousPage() {
		offset -= PAGESIZE;
	}

	public void toggleFrequency(Frequency frequency) {
		if (selectedFrequencies.contains(frequency)) {
			selectedFrequencies.remove(frequency);
		} else {
			selectedFrequencies.add(frequency);
		}
		offset = 0;
	}

	public boolean isFrequencySelected(Frequency frequency) {
		return selectedFrequencies.contains(frequency);
	}

	public void toggleSourceType(RepositoryType type) {
		if (selectedTypes.contains(type)) {
			selectedTypes.remove(type);
		} else {
			selectedTypes.add(type);
		}
		offset = 0;
	}

	public boolean isTypeSelected(RepositoryType type) {
		return selectedTypes.contains(type);
	}

	public void toggleCountry(String country) {
		if (selectedCountries.contains(country)) {
			selectedCountries.remove(country);
		} else {
			selectedCountries.add(country);
		}
		offset = 0;
	}

	public boolean isCountrySelected(String country) {
		return selectedCountries.contains(country);
	}

	public Long getFrequencyCounter(Frequency frequency) {
		return frequencyCounters.containsKey(frequency) ? frequencyCounters.get(frequency) : Long.valueOf(0);
	}

	public Long getTypeCounter(RepositoryType type) {
		return typeCounters.containsKey(type) ? typeCounters.get(type) : Long.valueOf(0);
	}

	public Long getCountryCounter(String country) {
		String ref = mdrCountries.getEurope(localization.getLocaleCode()).get(country);
		return countryCounters.containsKey(ref) ? countryCounters.get(ref) : Long.valueOf(0);
	}

	public void sortAlphabetically() {
		sort = sort == 1 ? 2 : 1;
	}

	public void sortSchedule() {
		sort = sort == 3 ? 4 : 3;
	}

	public int getSort() {
		return sort;
	}

}

src/main/java/de/fhg/fokus/odp/harvester/actions/RepositoryAction.java
package de.fhg.fokus.odp.harvester.actions;

import java.io.IOException;
import java.io.Serializable;
import java.util.*;
import java.util.stream.Collectors;

import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

import de.fhg.fokus.odp.harvester.application.InspireAdapter;
import de.fhg.fokus.odp.harvester.application.InspireHarvesterInfo;
import org.picketlink.Identity;

import de.fhg.fokus.odp.harvester.application.AppLocalization;
import de.fhg.fokus.odp.harvester.persistence.RepositoriesManager;
import de.fhg.fokus.odp.harvester.persistence.entities.Repository;
import de.fhg.fokus.odp.harvester.persistence.enums.RepositoryLanguage;
import de.fhg.fokus.odp.harvester.persistence.enums.RepositoryType;
import de.fhg.fokus.odp.harvester.persistence.enums.Visibility;
import de.fhg.fokus.odp.harvester.rdf.CountriesAuthorityTable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Named
@ViewScoped
public class RepositoryAction implements Serializable {

	private static final long serialVersionUID = -2683217693428389360L;

	protected final Logger log = LoggerFactory.getLogger(getClass());

	@Inject
	private RepositoriesManager repositoriesManager;

	@Inject
	private Identity identity;

	@Inject
	private AppLocalization localization;

	@Inject
	private CountriesAuthorityTable mdrCountries;

	@Inject
	private InspireAdapter inspireAdapter;

	private Repository repository;

	private Integer id;

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	private List<String> inspireTypeNames = new ArrayList<>();
	private List<Boolean> inspireTypeValues = new ArrayList<>();

	@Transactional
	public void load() {
		inspireAdapter.fetchHarvesters();
		inspireTypeNames.addAll(inspireAdapter.getHarvesters().stream().map(i -> i.getType()).collect(Collectors.toSet()));
		inspireTypeNames.forEach(name -> inspireTypeValues.add(Boolean.TRUE));

		if (id != null) {
			repository = repositoriesManager.find(id);
		} else {
			repository = new Repository();
			repository.setRepositoryType(RepositoryType.ckan);
			repository.setLanguage(RepositoryLanguage.ENGLISH);
			repository.setVisibility(Visibility.private_visibility);
			repository.setOwner(identity.getAccount().getId());
		}
	}

	@Transactional
	public void save() {
		if (id == null && repositoriesManager.nameExists(repository.getName())) {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrNameExists", null);
		} else {
			if (id == null) {
				repositoriesManager.persist(repository);
				id = repository.getId();
				AppLocalization.showMessage(FacesMessage.SEVERITY_INFO, "msgInfoRepoCreated", null);
			} else {
				repository = repositoriesManager.update(repository);
				AppLocalization.showMessage(FacesMessage.SEVERITY_INFO, "msgInfoRepoUpdated", null);
			}
		}
	}

	//Delete Repository from within Repository itself. Redirect to Dashboard
	@Transactional
	public String delete() {
		if (!repositoriesManager.isRepositoryInUse(repository)) {
			repositoriesManager.remove(repository);
			return "/user/dashboard?faces-redirect=true";
		} else {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrRepoInUse", null);
			return null;
		}
	}

	//Delete Repositories from Repositories list. Reloads Page
	@Transactional
	public void delete(Repository repository) throws IOException {
		repositoriesManager.remove(repository);
		FacesContext.getCurrentInstance().getExternalContext().redirect("/MetadataTransformerService/public/repositories.xhtml");
	}

	@Produces
	@Named
	public Repository getRepository() {
		return repository;
	}

	public Visibility[] getVisibilities() {
		return Visibility.values();
	}

	public RepositoryLanguage[] getLanguages() {
		return RepositoryLanguage.values();
	}

	public Map<String, String> getCountries() {
		return mdrCountries.getEurope(localization.getLocaleCode());
	}

	public void setSpatial(Set<String> spatial) {
		repository.setSpatial(spatial);
	}

	public Set<String> getSpatial() {
		return repository.getSpatial() != null ? new HashSet<>(repository.getSpatial()) : null;
	}

	public long countSelectedTypes(String selectedType) {
		return inspireAdapter.getHarvesters().stream().filter(i -> i.getType().equals(selectedType)).count();
	}

	public List<InspireHarvesterInfo> getInspireHarvesters() {
		return inspireAdapter.getHarvesters().stream().filter(i -> inspireTypeValues.get(inspireTypeNames.indexOf(i.getType()))).collect(Collectors.toList());
	}

	public void applyInspireHarvester(InspireHarvesterInfo info) {
		repository.setName(info.getName());
		repository.setDescription(info.getDescription());
		repository.setRepositoryType(RepositoryType.dcatap);
		repository.setUrl(info.getEndpoint());
		repository.setIncremental(info.isSelective());
	}

	public List<String> getInspireTypeNames() {
		return inspireTypeNames;
	}

	public List<Boolean> getInspireTypeValues() {
		return inspireTypeValues;
	}

	public void setInspireTypeValues(List<Boolean> values) {
		inspireTypeValues = values;
	}

}

src/main/java/de/fhg/fokus/odp/harvester/actions/UserAction.java
package de.fhg.fokus.odp.harvester.actions;

import java.io.Serializable;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

import de.fhg.fokus.odp.harvester.application.AppLocalization;
import de.fhg.fokus.odp.harvester.persistence.HarvestersManager;
import de.fhg.fokus.odp.harvester.persistence.RepositoriesManager;
import org.picketlink.Identity;
import org.picketlink.Identity.AuthenticationResult;
import org.picketlink.credential.DefaultLoginCredentials;
import org.picketlink.idm.IdentityManager;
import org.picketlink.idm.RelationshipManager;
import org.picketlink.idm.credential.Password;
import org.picketlink.idm.model.basic.BasicModel;
import org.picketlink.idm.model.basic.Grant;
import org.picketlink.idm.model.basic.User;

import de.fhg.fokus.odp.harvester.persistence.ActivitiesManager;

@Named
@RequestScoped
public class UserAction implements Serializable {

	private static final long serialVersionUID = -1533010002030134172L;
	
	private String password;
	private String confirmedPassword;

	private User user;
	
	@Inject
	private ActivitiesManager activitiesManager;

	@Inject
	private IdentityManager identityManager;

	@Inject
	private RelationshipManager relationshipManager;

	@Inject
	private RepositoriesManager repositoriesManager;

	@Inject
	private HarvestersManager harvestersManager;

	@Inject
	private Identity identity;
	
	@Inject
	private DefaultLoginCredentials credentials;
	
	@PostConstruct
	public void init() {
		if (identity.isLoggedIn()) {
			user = (User) identity.getAccount();
		} else {
			user = new User();
		}
	}
	
	@Transactional
	public String register() {
		
		// check input
		// 1. username not exist
		// 2. password confirmed
		User check = BasicModel.getUser(identityManager, user.getLoginName());
		if (check != null) {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrNameExists", null);
			return "";
		}
		
		if (!password.equals(confirmedPassword)) {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrUserPwMismatch", null);
			return "";
		}
		
		identityManager.add(user);
		identityManager.updateCredential(user, new Password(password));

		Grant grant = new Grant(user, BasicModel.getRole(identityManager, "User"));
		relationshipManager.add(grant);

		activitiesManager.userCreated(user, null);
		
		credentials.setUserId(user.getLoginName());
		credentials.setPassword(password);
		identity.login();
		
		return "/user/dashboard?faces-redirect=true";
	}

	public String login() {
		AuthenticationResult result = identity.login();
		if (result == AuthenticationResult.SUCCESS) {
			return "dashboard?faces-redirect=true";			
		} else {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrUserAuthFail", null);
			return null;
		}
	}
	
	public String logout() {
		identity.logout();
		return "/public/home?faces-redirect=true";
	}

	// doesn't work, throws IdentityManagementException
	public String removeUser() {
		// don't delete account if repositories or harvesters are still attached
		if (repositoriesManager.countUserRepositories() > 0 || harvestersManager.countUserHarvesters() > 0) {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrUserDeleteFail", null);
			return null;
		} else {
			String redirect = logout();
			identityManager.remove(user);
			return redirect;
		}
	}

	/**
	 * Builds the URL to request a profile picture from gravatar
	 * https://de.gravatar.com/
	 *
	 * @return A valid gravatar URL if a hash has been generated successfully and null otherwise
	 */
	public String getGravatarRequest() {
		String request = "https://www.gravatar.com/avatar/";

		if (getTrimmedAndHashedEmail() != null) {
			request += getTrimmedAndHashedEmail() + "?d=mm";
		} else {
			request += "?d=mm&f=y";
		}

		return request;
	}

	/**
	 * Trims and lowercases the currently logged in user's eMail and calculates an MD5 hash.
	 * This is required by the gravatar service for the fetching of profile pictures.
	 *
	 * @return 	MD5 hash of trimmed and lowercased email. Hash is also converted to lowercase
	 * 			Returns null in case an exception is thrown
	 */
	private String getTrimmedAndHashedEmail() {
		if (user.getEmail() == null) {
			return null;
		}

		String hashAsString = null;
		String preparedEmail = user.getEmail().trim().toLowerCase();

		try {

			// Calculate MD5 Hash
			MessageDigest md = MessageDigest.getInstance("MD5");
			md.update(preparedEmail.getBytes());
			byte hashedEmail[] = md.digest();

			// Convert MD5 byte stream to String representation
			StringBuilder sb = new StringBuilder();
			for (byte b : hashedEmail)
				sb.append(Integer.toHexString((b & 0xFF) | 0x100).substring(1,3));

			hashAsString = sb.toString().toLowerCase();

		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}

		return hashAsString;
	}

	@Transactional
	public void save() {
		if (password != null) {
			if (password.equals(confirmedPassword)) {
				identityManager.updateCredential(user, new Password(password));
			} else {
				AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrorPasswordChange", null);
			}
		}
		identityManager.update(user);
		// evaluate and apply new password if necessary
		AppLocalization.showMessage(FacesMessage.SEVERITY_INFO, "msgInfoUserUpdated", null);
	}

	public String getUsername() {
		return user.getLoginName();
	}

	public void setUsername(String username) {
		user.setLoginName(username);
	}

	public String getFirstName() {
		return user.getFirstName();
	}

	public void setFirstName(String firstName) {
		user.setFirstName(firstName);
	}

	public String getLastName() {
		return user.getLastName();
	}

	public void setLastName(String lastName) {
		user.setLastName(lastName);
	}

	public String getEmail() {
		return user.getEmail();
	}

	public void setEmail(String email) {
		user.setEmail(email);
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getConfirmedPassword() {
		return confirmedPassword;
	}

	public void setConfirmedPassword(String password) {
		this.confirmedPassword = password;
	}

}

src/main/webapp/user/dashboard.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
		xmlns:f="http://xmlns.jcp.org/jsf/core"
		xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
		xmlns:pf="http://primefaces.org/ui">
<h:body role="document">
	<ui:composition template="../templates/main.xhtml">

		<ui:define name="metadata">
			<f:metadata>
				<f:viewAction action="${dashboardController.load}"/>
			</f:metadata>
		</ui:define>

		<ui:define name="title">${localized.titleDashboard}</ui:define>

		<ui:define name="content">
			<div class="page-header">
				<div class="media">
					<div class="media-left">
						<h:graphicImage alt="${localized.altProfilePicture}" url="#{userAction.gravatarRequest}" />
					</div>
					<div class="media-body media-bottom">
						<h1 class="media-heading">
							${identity.account.loginName} <small>${localized.titleDashboard}</small>
						</h1>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8">
					<h:form>
						<h:panelGroup id="recentHarvestersList">
							<h2>${localized.labelHarvesterRecentlyFinished} <span class="badge">${dashboardController.listRecentlyFinishedHarvesters().size()}</span></h2>
							<ui:repeat var="harv" value="${dashboardController.listRecentlyFinishedHarvesters()}">
								<ui:include src="../templates/harvesterpanel.xhtml" />
							</ui:repeat>
						</h:panelGroup>
						<h:panelGroup id="runningHarvestersList">
							<h2>${localized.labelHarvesterCurrentlyRunning} <span class="badge">${dashboardController.listRunningHarvesters().size()}</span></h2>
							<ui:repeat var="harv" value="${dashboardController.listRunningHarvesters()}">
								<ui:include src="../templates/harvesterpanel.xhtml" />
							</ui:repeat>
						</h:panelGroup>
						<h:panelGroup id="scheduledHarvestersList">
							<h2>${localized.labelHarvesterScheduled} <span class="badge">${dashboardController.listScheduledHarvesters().size()}</span></h2>
							<ui:repeat var="harv" value="${dashboardController.listScheduledHarvesters()}">
								<ui:include src="../templates/harvesterpanel.xhtml" />
							</ui:repeat>
						</h:panelGroup>
						<pf:poll interval="2" update="recentHarvestersList runningHarvestersList scheduledHarvestersList" listener="#{dashboardController.refresh}"/>
					</h:form>
				</div>
				<div class="col-md-4">
					<div class="panel panel-info">
						<div class="panel-heading">${localized.infoMiscPanelHeaderStatistics}</div>
						<ul class="list-group">
							<li class="list-group-item">
								${localized.labelHarvesterOwned}<span class="badge">${dashboardController.countUserHarvesters()}</span>
							</li>
							<li class="list-group-item">
								${localized.labelRepositoryOwned}<span class="badge">${repositoryController.countUserRepositories()}</span>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/user/profile.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
<h:body role="document">
	<ui:composition template="../templates/main.xhtml">

		<ui:define name="title">${localized.titleProfile}</ui:define>

		<ui:define name="content">
			<div class="page-header">
				<div class="media">
					<div class="media-left">
						<h:graphicImage alt="${localized.altProfilePicture}" url="#{userAction.gravatarRequest}" />
					</div>
					<div class="media-body media-bottom">
						<h1 class="media-heading">
							${identity.account.loginName} <small>${localized.titleProfile}</small>
						</h1>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-8">
					<h:form styleClass="form-horizontal" id="formProfileInput">

						<h:messages styleClass="list-unstyled" errorClass="alert alert-danger" infoClass="alert alert-success" warnClass="alert alert-warning" p:role="alert" />

						<div class="form-group">
							<label for="inputUsername" class="col-sm-3 control-label">${localized.inputProfileUsername}</label>
							<div class="col-sm-9">
								<h:inputText disabled="true" value="#{userAction.username}" required="true" styleClass="form-control" id="inputUsername" />
							</div>
						</div>
						<div class="form-group">
							<label for="inputFirstName" class="col-sm-3 control-label">${localized.inputProfileFirstname}</label>
							<div class="col-sm-9">
								<h:inputText value="#{userAction.firstName}"  p:placeholder="${localized.inputProfileFirstname}" styleClass="form-control" p:type="text" id="inputFirstName" />
							</div>
						</div>
						<div class="form-group">
							<label for="inputSurname" class="col-sm-3 control-label">${localized.inputProfileLastname}</label>
							<div class="col-sm-9">
								<h:inputText value="#{userAction.lastName}" p:placeholder="${localized.inputProfileLastname}" styleClass="form-control" p:type="text" id="inputSurname" />
							</div>
						</div>
						<div class="form-group">
							<label for="inputOrganisation" class="col-sm-3 control-label">${localized.inputProfileOrganisation}</label>
							<div class="col-sm-9">
								<h:inputText p:placeholder="${localized.inputProfileOrganisation}" styleClass="form-control" p:type="text" id="inputOrganisation" />
							</div>
						</div>
						<div class="form-group">
							<label for="inputEmail" class="col-sm-3 control-label">${localized.inputProfileEmail}</label>
							<div class="col-sm-9">
								<h:inputText value="#{userAction.email}" p:placeholder="${localized.inputProfileEmail}" styleClass="form-control" required="true" p:type="email" id="inputEmail" />
							</div>
						</div>
						<div class="form-group">
							<label for="inputDescription" class="col-sm-3 control-label">${localized.inputMiscDescription}</label>
							<div class="col-sm-9">
								<h:inputTextarea required="false" styleClass="form-control" id="inputDescription" />
							</div>
						</div>
						<div class="collapse" id="collapseMore">
							<div class="form-group">
								<label for="inputPassword" class="col-sm-3 control-label">${localized.inputMiscPassword}</label>
								<div class="col-sm-9">
									<h:inputSecret value="#{userAction.password}" p:placeholder="${localized.inputPassword}" styleClass="form-control" p:type="password" id="inputPassword" />
								</div>
							</div>
							<div class="form-group">
								<label for="inputConfirmPassword" class="col-sm-3 control-label">${localized.inputMiscConfirmPassword}</label>
								<div class="col-sm-9">
									<h:inputSecret value="#{userAction.confirmedPassword}" p:placeholder="${localized.inputConfirmPassword}" styleClass="form-control" p:type="password" id="inputConfirmPassword" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-offset-3 col-sm-9">
								<h:commandButton value="${localized.buttonMiscApply}" action="#{userAction.save()}" styleClass="btn btn-primary" id="buttonApply" />
								<span style="margin-left:10px;" />
								<a class="btn btn-info" role="button" id="buttonExpandPassword" data-toggle="collapse" href="#collapseMore" aria-expanded="false" aria-controls="collapseMore">${localized.buttonProfilePasswordChange}</a>
                                <span style="margin-left: 10px;" />
                                <h:commandButton disabled="true" value="${localized.buttonProfileRemoveAccount}" action="#{userAction.removeUser}" styleClass="btn btn-danger" id="buttonRemove"/>
                            </div>
						</div>
					</h:form>
				</div>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>