src/main/java/de/fhg/fokus/odp/harvester/persistence/entities/Harvester.java
package de.fhg.fokus.odp.harvester.persistence.entities;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.*;

import de.fhg.fokus.odp.harvester.util.TransformationScriptDownloader;
import de.fhg.fokus.odp.harvester.persistence.enums.Frequency;
import de.fhg.fokus.odp.harvester.persistence.enums.HarvesterEnums;
import de.fhg.fokus.odp.harvester.persistence.enums.Visibility;

@Entity
@NamedQueries({
        @NamedQuery(name = "harvesters", query = "select h from Harvester h order by h.name"),
        @NamedQuery(name = "harvesters_of_visibility", query = "select h from Harvester h where h.visibility = :visibility order by h.name"),
        @NamedQuery(name = "harvesters_of_visibility_or_from_owner", query = "select h from Harvester h where h.visibility = :visibility or h.owner = :owner order by h.name"),
        @NamedQuery(name = "harvesters_from_owner", query = "select h from Harvester h where h.owner = :owner order by h.name"),
        @NamedQuery(name = "harvesters_search", query = "select h from Harvester h where lower(h.name) like :searchterm and h.visibility = :visibility order by h.name"),
        @NamedQuery(name = "harvesters_search_from_owner", query = "select distinct h from Harvester h where lower(h.name) like :searchterm and (h.owner = :owner or h.visibility = :visibility) order by h.name"),
        @NamedQuery(name = "harvesters_running", query = "select h from Harvester h join h.runs r where h.owner = :owner and r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.running order by r.startTime desc"),
        @NamedQuery(name = "harvesters_finished_from_owner", query = "select h from Run r join r.harvester h where h.owner = :owner and r.runState <> de.fhg.fokus.odp.harvester.persistence.enums.RunState.running and r.endTime is not null order by r.endTime desc"),
        @NamedQuery(name = "harvesters_scheduled_from_owner", query = "select h from Harvester h where h.owner = :owner and h.frequency <> de.fhg.fokus.odp.harvester.persistence.enums.Frequency.manually order by h.nextHarvestDate asc"),
        @NamedQuery(name = "harvesters_with_errors", query = "SELECT DISTINCT h from Harvester h JOIN h.runs r WHERE r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error"),
        @NamedQuery(name = "harvesters_with_errors_from_owner", query = "SELECT DISTINCT h from Harvester h JOIN h.runs r WHERE r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error AND h.owner = :owner order by h.name"),
        @NamedQuery(name = "harvesters_with_errors_of_visibility", query = "SELECT DISTINCT h from Harvester h JOIN h.runs r WHERE r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error AND h.visibility = :visibility"),
        @NamedQuery(name = "harvesters_with_errors_of_visibility_or_from_owner", query = "SELECT DISTINCT h from Harvester h JOIN h.runs r WHERE r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error AND (h.visibility = :visibility or h.owner = :owner)"),
        @NamedQuery(name = "harvesters_search_with_errors", query = "SELECT DISTINCT h from Harvester h JOIN h.runs r WHERE r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error AND lower(h.name) like :searchterm and h.visibility = :visibility"),
        @NamedQuery(name = "harvesters_search_with_errors_from_owner", query = "SELECT DISTINCT h from Harvester h JOIN h.runs r WHERE r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error AND lower(h.name) like :searchterm and (h.owner = :owner or h.visibility = :visibility)")
})
public class Harvester {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    private String name;

    @ManyToOne(fetch = FetchType.EAGER)
    private Repository source;

    @ManyToOne(fetch = FetchType.EAGER)
    private Repository target;

    private String sourceApiKey;

    private String targetApiKey;

    private Integer threadCount = 1;

    private String description;

    @OneToMany(mappedBy = "harvester", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private List<Activity> activities;

    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("index asc")
    private Set<Filter> filters;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "harvester", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("startTime desc")
    private Set<Run> runs;

    private boolean emailNotification = false;

    private String owner;

    @Enumerated(EnumType.STRING)
    private HarvesterEnums.TransformationScriptSource transformationScriptSource;

    private String gitRepoUrl;

    private String gitBranch;

    private String gitFileName;

    private boolean gitRepoRequiresCredentials;

    private boolean gitRepoSshAuthentication;

    /*
    JGit can only handle plain text credentials
     */
    private String gitUserName;

    private String gitPassWord;

    @Lob
    private String mappingScript;

    @Enumerated(EnumType.STRING)
    private Frequency frequency;

    @Enumerated(EnumType.STRING)
    private Visibility visibility;

    @Enumerated(EnumType.STRING)
    private HarvesterEnums.HarvestStrategy harvestStrategy = HarvesterEnums.HarvestStrategy.create;

    @Temporal(TemporalType.TIMESTAMP)
    private Date nextHarvestDate;

    @Temporal(TemporalType.TIMESTAMP)
    private Date created;

    @Temporal(TemporalType.TIMESTAMP)
    private Date updated;

    private boolean forceUpdate;

    public Harvester() {
        filters = new HashSet<>();
        runs = new HashSet<>();
    }

    public List<Activity> getActivities() {
        return this.activities;
    }

    public void setActivities(List<Activity> acts) {
        this.activities = acts;
    }

    @PrePersist
    public void onPersist() {
        created = new Date();
    }

    @PreUpdate
    public void onUpdate() {
        updated = new Date();
    }

    public boolean getEmailNotification() {
        return emailNotification;
    }

    public void setEmailNotification(boolean emailNotification) {
        this.emailNotification = emailNotification;
    }

    public Date getUpdated() {
        return updated;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getNextHarvestDate() {
        return this.nextHarvestDate;
    }

    public void setNextHarvestDate(Date nextHarvestDate) {
        this.nextHarvestDate = nextHarvestDate;
    }

    public String getReadableTimeStamp() {
        return new SimpleDateFormat("EEE, MMM d, HH:mm").format(nextHarvestDate);
    }

    public Frequency getFrequency() {
        return this.frequency;
    }

    public void setFrequency(Frequency frequency) {
        this.frequency = frequency;
    }

    public Visibility getVisibility() {
        return this.visibility;
    }

    public void setVisibility(Visibility visibility) {
        this.visibility = visibility;
    }

    public Integer getThreadCount() {
        return threadCount;
    }

    public void setThreadCount(Integer threadCount) {
        this.threadCount = threadCount;
    }

    public Set<Filter> getFilters() {
        return this.filters;
    }

    //Sorts all filters with the enabled flag set ascending by their index
    public List<Filter> getEnabledAndSortedFilters() {
        List<Filter> result = filters.stream().filter(Filter::isFilterEnabled).collect(Collectors.toList());
        result.sort((f1, f2) -> f1.getIndex() - f2.getIndex());
        return result;
    }

    public void setFilters(Set<Filter> filters) {
        this.filters = filters;
    }

    public Set<Run> getRuns() {
        return this.runs;
    }

    public void setRuns(Set<Run> runs) {
        this.runs = runs;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTargetApiKey() {
        return this.targetApiKey;
    }

    public void setTargetApiKey(String targetApiKey) {
        this.targetApiKey = targetApiKey;
    }

    public String getSourceApiKey() {
        return this.sourceApiKey;
    }

    public void setSourceApiKey(String sourceApiKey) {
        this.sourceApiKey = sourceApiKey;
    }

    public Repository getTarget() {
        return this.target;
    }

    public void setTarget(Repository target) {
        this.target = target;
    }

    public Repository getSource() {
        return this.source;
    }

    public void setSource(Repository source) {
        this.source = source;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSampleTransformationFileName() {
        if ((getSource() != null) && (getTarget() != null)) {
            return getSource().getRepositoryType().name() + "-to-" + getTarget().getRepositoryType().name() + ".script";
        }
        return null;
    }

    //Return the plain script or contents of a file from git
    public String getMappingScript() {
        return mappingScript;
    }

    public void setMappingScript(String mappingScript) {
        this.mappingScript = mappingScript;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public HarvesterEnums.TransformationScriptSource getTransformationScriptSource() {
        return transformationScriptSource;
    }

src/main/java/de/fhg/fokus/odp/harvester/persistence/entities/Run.java
package de.fhg.fokus.odp.harvester.persistence.entities;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

import de.fhg.fokus.odp.harvester.persistence.enums.RunState;

@Entity
@NamedQueries({
        @NamedQuery(name = "runs_by_harvester_id", query = "select r from Run r where r.harvester.id = :id order by r.startTime desc"),
        @NamedQuery(name = "runs_with_status", query = "select r from Run r where r.harvester.id = :id and r.runState = :runstatus order by r.startTime desc"),
        @NamedQuery(name = "count_runs_with_status", query = "select count(r) from Run r where r.harvester.id = :id and r.runState = :runstatus"),
        @NamedQuery(name = "count_runs_by_harvester_id", query = "select count(r) from Run r where r.harvester.id = :id"),
        @NamedQuery(name = "completed_runs_by_date", query = "select r from Run r where r.harvester.id = :id " +
                "and (r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error " +
                "or r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.interrupted " +
                "or r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.finished) " +
                "order by r.startTime desc"),
        @NamedQuery(name = "completed_runs_by_status", query = "select r from Run r where r.harvester.id = :id " +
                "and (r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error " +
                "or r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.interrupted " +
                "or r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.finished) " +
                "order by r.runState desc"),
        @NamedQuery(name = "count_completed_runs", query = "select count(r) from Run r where r.harvester.id = :id " +
                "and (r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.error " +
                "or r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.interrupted " +
                "or r.runState = de.fhg.fokus.odp.harvester.persistence.enums.RunState.finished)")
})
public class Run {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Enumerated(EnumType.STRING)
    private RunState runState;

    @Temporal(TemporalType.TIMESTAMP)
    private Date startTime;

    @Temporal(TemporalType.TIMESTAMP)
    private Date endTime;

    @OneToMany(mappedBy = "run", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @OrderBy("created desc")
    private List<Log> logs = new ArrayList<>();

    private Integer numberToProcess = 0;

    private Integer numberAdded = 0;

    private Integer numberUpdated = 0;

    private Integer numberSkipped = 0;

    private Integer numberRejected = 0;

    private Integer numberDeleted = 0;

    private boolean incremental;

    @ManyToOne
    private Harvester harvester;

    public Harvester getHarvester() {
        return harvester;
    }

    public void setHarvester(Harvester harvester) {
        this.harvester = harvester;
    }

    public List<Log> getLogs() {
        return this.logs;
    }

    public void setLogs(List<Log> logs) {
        this.logs = logs;
    }

    public RunState getRunState() {
        return this.runState;
    }

    public void setRunState(RunState runState) {
        this.runState = runState;
    }

    public Integer getNumberAdded() {
        return numberAdded;
    }

    public void setNumberAdded(Integer numberAdded) {
        this.numberAdded = numberAdded;
    }

    public Integer getNumberUpdated() {
        return numberUpdated;
    }

    public void setNumberUpdated(Integer numberUpdated) {
        this.numberUpdated = numberUpdated;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getDayOfRunStart() {
        return new SimpleDateFormat("yyyy-MM-dd").format(startTime);
    }

    public String getTimeWithoutDay(Date time) {
        return new SimpleDateFormat("HH:mm:ss").format(time);
    }


    public Long getRunDurationInMinutes() {
        if (startTime == null || endTime == null) {
            return 0L;
        }
        return (endTime.getTime() - startTime.getTime()) / (1000 * 60);
    }

    public Integer getNumberToProcess() {
        return numberToProcess;
    }

    public void setNumberToProcess(Integer numberToProcess) {
        this.numberToProcess = numberToProcess;
    }

    public Integer getNumberRejected() {
        return numberRejected;
    }

    public void setNumberRejected(Integer numberRejected) {
        this.numberRejected = numberRejected;
    }

    public Integer getNumberSkipped() {
        return numberSkipped;
    }

    public void setNumberSkipped(Integer numberSkipped) {
        this.numberSkipped = numberSkipped;
    }

    public Integer getNumberDeleted() {
        return numberDeleted;
    }

    public void setNumberDeleted(Integer numberDeleted) {
        this.numberDeleted = numberDeleted;
    }

    public boolean isIncremental() {
        return incremental;
    }

    public void setIncremental(boolean incremental) {
        this.incremental = incremental;
    }

}

src/main/java/de/fhg/fokus/odp/harvester/actions/DashboardController.java
package de.fhg.fokus.odp.harvester.actions;

import de.fhg.fokus.odp.harvester.persistence.HarvestersManager;
import de.fhg.fokus.odp.harvester.persistence.entities.Harvester;
import org.picketlink.Identity;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;
import java.io.Serializable;
import java.util.List;

/**
 * Created by sim on 26.06.2017.
 */
@Named
@ViewScoped
public class DashboardController implements Serializable {

    @Inject
    private Identity identity;

    @Inject
    private HarvestersManager harvestersManager;

    private List<Harvester> recentlyFinished;
    private List<Harvester> running;
    private List<Harvester> scheduled;

    @Transactional
    public void load() {
        recentlyFinished = harvestersManager.listRecentlyFinishedHarvesters(3);
        running = harvestersManager.listRunningHarvesters();
        scheduled = harvestersManager.listScheduledHarvesters(5);
    }

    public List<Harvester> listRunningHarvesters() {
        return running;
    }

    public List<Harvester> listScheduledHarvesters() {
        return scheduled;
    }

    public List<Harvester> listRecentlyFinishedHarvesters() {
        return recentlyFinished;
    }

    public int countUserHarvesters() {
        return harvestersManager.countUserHarvesters().intValue();
    }

    @Transactional
    public void refresh() {
        recentlyFinished = harvestersManager.listRecentlyFinishedHarvesters(3);
        running = harvestersManager.listRunningHarvesters();
        scheduled = harvestersManager.listScheduledHarvesters(5);
    }
}

src/main/webapp/templates/harvesterpanel.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
	<div class="panel">
		<div class="panel-heading" style="padding:0px;">
			<h:link rendered="${harv.owner eq identity.account.id}" styleClass="btn #{harv.visibility == 'public_visibility' ? 'btn-primary' : 'btn-info'}" style="display:block;" outcome="/public/showharvester?faces-redirect=true">
				<f:param name="id" value="#{harv.id}" />
				<div class="row">
					<div class="col-sm-6 text-left">
						<i class="fa ${harvesterAction.isRunning(harv) ? 'fa-refresh fa-spin' : 'fa-power-off'}" /> ${harv.name}
					</div>
					<div class="col-sm-3 text-right">
						<i class="fa fa-user" /> ${userManager.getUser(harv.owner).loginName}
					</div>
					<div class="col-sm-3 text-right">
						<i class="fa #{harv.visibility == 'public_visibility' ? 'fa-share' : 'fa-lock'}" /> ${localized['visibility' += harv.visibility.label]}
					</div>
				</div>
			</h:link>
		</div>
		<div class="panel-body">
			${harv.description}
		</div>
		<div class="panel-footer">
			<div class="row">
				<div class="col-sm-2 text-left">
					<span>${localized['harvestFrequency' += harv.frequency.label]} </span>
					<ui:fragment rendered="${harv.source.incremental}">
						<i class="fa fa-filter" title="${localized.inputIncremental}" />
					</ui:fragment>
				</div>
				<div class="col-sm-7">
					<ui:fragment rendered="${harv.frequency ne 'manually'}">
						<span class="text-warning">${localized.nextRun}: ${harv.readableTimeStamp}</span>
					</ui:fragment>
				</div>
				<div class="col-sm-3 text-right">
					<ui:fragment rendered="${(harv.source ne null) and (harv.target ne null)}">
						<h:link id="buttonHarvesterShow" outcome="/user/editharvester?faces-redirect=true">
							<f:param name="id" value="#{harv.id}" />
							<i class="fa fa-edit" />
						</h:link>
					</ui:fragment>
				</div>
			</div>
		</div>
	</div>
</html>

src/main/webapp/templates/loginmenu.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
	<h:form>
		<ul class="nav navbar-nav navbar-right">

			<ui:fragment rendered="${not identity.loggedIn}">
				<li id="menuLogin" class="${request.servletPath == '/user/login' ? 'active' : ''}">
					<h:link outcome="/user/login?faces-redirect=true">
						<i class="fa fa-sign-in fa-fw" aria-hidden="true" /> ${localized.linkProfileLogin}
					</h:link>

				</li>

				<!-- 			<li class="${request.servletPath == '/public/registration' ? 'active' : ''}"><h:commandLink value="${localized.linkRegistration}" action="/public/registration?faces-redirect=true" /></li>  -->
			</ui:fragment>

			<ui:fragment rendered="${identity.loggedIn}">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-fw" aria-hidden="true" /> ${identity.account.loginName} <span class="caret" /></a>
					<ul class="dropdown-menu">
						<li id="menuDashboard">
							<h:link outcome="/user/dashboard?faces-redirect=true"><i class="fa fa-dashboard fa-fw" aria-hidden="true" /> ${localized.titleDashboard}</h:link>
						</li>
						<ui:fragment rendered="${request.isUserInRole('Administrator')}">
							<li id="menuSchedulings">
								<h:link outcome="/protected/schedulings?faces-redirect=true"><i class="fa fa-clock-o fa-fw" aria-hidden="true" /> ${localized.schedulingsTitle}</h:link>
							</li>
							<li id="menuUsers" aria-disabled="true">
								<h:link outcome="/protected/users?faces-redirect=true"><i class="fa fa-users fa-fw" aria-hidden="true" /> User Management</h:link>
							</li>
						</ui:fragment>
						<li id="menuProfile">
							<h:link outcome="/user/profile?faces-redirect=true"><i class="fa fa-user fa-fw" aria-hidden="true" /> ${localized.titleProfile}</h:link>
						</li>
						<li role="separator" class="divider" />
						<li id="menuLogout">
							<a href="../logout"><i class="fa fa-sign-out fa-fw" aria-hidden="true" /> ${localized.linkProfileLogout}</a>
						</li>
					</ul>
				</li>
			</ui:fragment>

			<li id="menuHelp" class="${request.servletPath == '/public/help.xhtml' ? 'active' : ''}">
				<h:link outcome="/public/help?faces-redirect=true">
					<i class="fa fa-graduation-cap fa-fw" aria-hidden="true" /> ${localized.titleHelp}
				</h:link>
			</li>

			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-language fa-fw" aria-hidden="true" /> ${appLocalization.language} <span class="caret" /></a>
				<ul class="dropdown-menu">
        		    <li><h:commandLink value="${appLocalization.languageName('de')}" action="#{appLocalization.changeLanguage('de')}" /></li>
        		    <li><h:commandLink value="${appLocalization.languageName('en')}" action="#{appLocalization.changeLanguage('en')}" /></li>
        		    <li><h:commandLink value="${appLocalization.languageName('es')}" action="#{appLocalization.changeLanguage('es')}" /></li>
        		    <li><h:commandLink value="${appLocalization.languageName('fr')}" action="#{appLocalization.changeLanguage('fr')}" /></li>
        		    <li><h:commandLink value="${appLocalization.languageName('it')}" action="#{appLocalization.changeLanguage('it')}" /></li>
        		    <li><h:commandLink value="${appLocalization.languageName('pl')}" action="#{appLocalization.changeLanguage('pl')}" /></li>
		    	</ul>
        	</li>
       	</ul>
	</h:form>
</html>

src/main/webapp/templates/runpanel.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <div class="panel panel-${run.runState == 'finished' ? 'success' : run.runState == 'interrupted' ? 'warning' : 'danger'}">
        <div class="panel-heading">
            <div class="row">
                <div class="col-sm-6">
                	<h:outputText value="${localized.labelRunTimeStart}:  " />
					<ui:fragment rendered="${run.startTime ne null}">
						<h:outputText value="${run.startTime}">
							<f:convertDateTime type="both" dateStyle="default"
								timeStyle="default" locale="#{appLocalization.localeCode}"
								timeZone="${appLocalization.timeZone}" />
						</h:outputText>
					</ui:fragment>
					<ui:fragment rendered="${run.startTime eq null}">
						${localized.labelMiscNotAvailable}
					</ui:fragment>
					<ui:fragment rendered="${run.incremental}">
						<i class="fa fa-filter" style="margin-left: 5px;" title="${localized.inputIncremental}" />
					</ui:fragment>
                </div>
                <div class="col-sm-6 text-right">
                    ${localized['runStatus' += run.runState.label]}
                </div>
            </div>
        </div>
        <div class="panel-body">
        	<div class="row">
        		<div class="col-sm-4">
	        		<p>${localized.labelRunProcessing}: <span class="badge" style="vertical-align:text-bottom;">${run.numberToProcess}</span></p>
        		</div>
        		<div class="col-sm-4">
	        		<p>${localized.labelRunAdded}: <span class="badge" style="vertical-align:text-bottom;">${run.numberAdded}</span></p>
        		</div>
        		<div class="col-sm-4">
	        		<p>${localized.labelMiscDeleted}: <span class="badge" style="vertical-align:text-bottom;">${run.numberDeleted}</span></p>
        		</div>
        	</div>
        	<div class="row">
        		<div class="col-sm-offset-4 col-sm-4">
	        		${localized.labelRunUpdated}: <span class="badge" style="vertical-align:text-bottom;">${run.numberUpdated}</span>
        		</div>
        		<div class="col-sm-4">
	        		${localized.labelRunRejected}: <span class="badge" style="vertical-align:text-bottom;">${run.numberRejected}</span>
        		</div>
        	</div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-5">
                	<h:outputText value="${localized.labelRunTimeEnd}:  " />
					<ui:fragment rendered="${run.endTime ne null}">
						<h:outputText value="${run.endTime}">
							<f:convertDateTime type="both" dateStyle="default"
								timeStyle="default" locale="#{appLocalization.localeCode}"
								timeZone="${appLocalization.timeZone}" />
						</h:outputText>
					</ui:fragment>
					<ui:fragment rendered="${run.endTime eq null}">
						${localized.labelMiscNotAvailable}
					</ui:fragment>
                </div>
                <div class="col-sm-5">
                	<h:outputText value="${localized.labelRunDuration}:  " />
					${run.runDurationInMinutes} ${run.runDurationInMinutes ne null ? (run.runDurationInMinutes eq 1 ? localized.unitMinuteSingular : localized.unitMinutePlural) : localized.labelMiscNotAvailable}
                </div>
                <div class="col-sm-2 text-right">
                    <h:link styleClass="text-info" outcome="/public/showrun?faces-redirect=true">
						<f:param name="id" value="#{run.id}" />
                        <i class="fa fa-eye" />
                    </h:link>
                </div>
            </div>
        </div>
    </div>
</html>