src/main/java/de/fhg/fokus/odp/harvester/actions/HarvesterController.java
package de.fhg.fokus.odp.harvester.actions;

import de.fhg.fokus.odp.harvester.application.AppLocalization;
import de.fhg.fokus.odp.harvester.persistence.HarvestersManager;
import de.fhg.fokus.odp.harvester.persistence.entities.Harvester;
import de.fhg.fokus.odp.harvester.persistence.entities.Repository;
import de.fhg.fokus.odp.harvester.persistence.enums.Frequency;
import de.fhg.fokus.odp.harvester.persistence.enums.RepositoryType;
import de.fhg.fokus.odp.harvester.rdf.CountriesAuthorityTable;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

import java.io.Serializable;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@Named
@ViewScoped
public class HarvesterController implements Serializable {

	private static final long serialVersionUID = -534693913871978425L;
	
	private String searchTerm = "";
	private boolean errorsOnly = false;

	private final Integer PAGESIZE = 15;

	private Integer offset = 0;

	private int sort = 1;

	@Inject
	private AppLocalization localization;

	@Inject
	private CountriesAuthorityTable mdrCountries;

	@Inject
	private HarvestersManager harvestersManager;

	private List<Harvester> harvesters;

	private List<Frequency> selectedFrequencies = new ArrayList<>();
	private Map<Frequency, Long> frequencyCounters = new HashMap<>();

	private List<RepositoryType> selectedTypes = new ArrayList<>();
	private Map<RepositoryType, Long> typeCounters = new HashMap<>();

	private List<String> selectedCountries = new ArrayList<>();
	private Map<String, Long> countryCounters = new HashMap<>();

	@Transactional
	public void load() {
		fetchlist();
	}

	@Transactional
	public void search() {
		fetchlist();
	}

	private void fetchlist() {
		offset = 0;
		harvesters = harvestersManager.listHarvesters(null, null, searchTerm, errorsOnly);
		frequencyCounters = harvesters.stream().collect(Collectors.groupingBy(Harvester::getFrequency, Collectors.counting()));
		typeCounters = harvesters.stream().map(Harvester::getSource).collect(Collectors.groupingBy(Repository::getRepositoryType, Collectors.counting()));
		countryCounters = harvesters.stream().map(Harvester::getSource).flatMap(r -> r.getSpatial().stream()).collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
	}

	public Integer getOffset() {
		return offset;
	}

	public void setOffset(Integer offset) {
		this.offset = offset < 0 ? 0 : offset;
	}

	public Long getTotal() {
		return getHarvestersStream().count();
	}

	public Long getRows() {
		long size = getTotal();
		return size - PAGESIZE > offset ? PAGESIZE : size - offset;
	}

	public List<Harvester> getAllHarvesters() {
		if (sort == 1 || sort == 2) {
			harvesters.sort(Comparator.comparing(Harvester::getName));
		} else {
			harvesters.sort(Comparator.nullsLast(Comparator.comparing(Harvester::getNextHarvestDate)));
		}
		if (sort == 2 || sort == 4) {
			Collections.reverse(harvesters);
		}
		return harvesters;
	}

	public List<Harvester> getHarvesters() {
		return getHarvestersStream().skip(offset).limit(PAGESIZE).collect(Collectors.toList());
	}

	private Stream<Harvester> getHarvestersStream() {
		Stream<Harvester> stream = harvesters.stream();
		if (!selectedFrequencies.isEmpty()) {
			stream = stream.filter(h -> selectedFrequencies.contains(h.getFrequency()));
		}
		if (!selectedTypes.isEmpty()) {
			stream = stream.filter(h -> selectedTypes.contains(h.getSource().getRepositoryType()));
		}
		if (!selectedCountries.isEmpty()) {
			stream = stream.filter(h -> h.getSource().getSpatial().stream().map(s -> mdrCountries.prefLabel(s, localization.getLocaleCode())).anyMatch(selectedCountries::contains));
		}
		return stream;
	}

	public Frequency[] getFrequencies() {
		return Frequency.values();
	}

	public RepositoryType[] getRepositoryTypes() {
		return RepositoryType.values();
	}

	public String[] getCountries() {
		return mdrCountries.getEurope(localization.getLocaleCode()).keySet().toArray(new String[] {});
	}

	public String getSearchTerm() {
		return searchTerm;
	}
	
	public void setSearchTerm(String searchTerm) {
		this.searchTerm = searchTerm;
	}

	public boolean isErrorsOnly() {
		return errorsOnly;
	}

	public void setErrorsOnly(boolean errorsOnly) {
		this.errorsOnly = errorsOnly;
	}

	@Transactional
	public void nextPage() {
		offset += PAGESIZE;
	}

	@Transactional
	public void previousPage() {
		offset -= PAGESIZE;
	}

	public void toggleFrequency(Frequency frequency) {
		if (selectedFrequencies.contains(frequency)) {
			selectedFrequencies.remove(frequency);
		} else {
			selectedFrequencies.add(frequency);
		}
		offset = 0;
	}

	public boolean isFrequencySelected(Frequency frequency) {
		return selectedFrequencies.contains(frequency);
	}

	public void toggleSourceType(RepositoryType type) {
		if (selectedTypes.contains(type)) {
			selectedTypes.remove(type);
		} else {
			selectedTypes.add(type);
		}
		offset = 0;
	}

	public boolean isTypeSelected(RepositoryType type) {
		return selectedTypes.contains(type);
	}

	public void toggleCountry(String country) {
		if (selectedCountries.contains(country)) {
			selectedCountries.remove(country);
		} else {
			selectedCountries.add(country);
		}
		offset = 0;
	}

	public boolean isCountrySelected(String country) {
		return selectedCountries.contains(country);
	}

	public Long getFrequencyCounter(Frequency frequency) {
		return frequencyCounters.containsKey(frequency) ? frequencyCounters.get(frequency) : Long.valueOf(0);
	}

	public Long getTypeCounter(RepositoryType type) {
		return typeCounters.containsKey(type) ? typeCounters.get(type) : Long.valueOf(0);
	}

	public Long getCountryCounter(String country) {
		String ref = mdrCountries.getEurope(localization.getLocaleCode()).get(country);
		return countryCounters.containsKey(ref) ? countryCounters.get(ref) : Long.valueOf(0);
	}

	public void sortAlphabetically() {
		sort = sort == 1 ? 2 : 1;
	}

	public void sortSchedule() {
		sort = sort == 3 ? 4 : 3;
	}

	public int getSort() {
		return sort;
	}

}

src/main/java/de/fhg/fokus/odp/harvester/actions/UserAction.java
package de.fhg.fokus.odp.harvester.actions;

import java.io.Serializable;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

import de.fhg.fokus.odp.harvester.application.AppLocalization;
import de.fhg.fokus.odp.harvester.persistence.HarvestersManager;
import de.fhg.fokus.odp.harvester.persistence.RepositoriesManager;
import org.picketlink.Identity;
import org.picketlink.Identity.AuthenticationResult;
import org.picketlink.credential.DefaultLoginCredentials;
import org.picketlink.idm.IdentityManager;
import org.picketlink.idm.RelationshipManager;
import org.picketlink.idm.credential.Password;
import org.picketlink.idm.model.basic.BasicModel;
import org.picketlink.idm.model.basic.Grant;
import org.picketlink.idm.model.basic.User;

import de.fhg.fokus.odp.harvester.persistence.ActivitiesManager;

@Named
@RequestScoped
public class UserAction implements Serializable {

	private static final long serialVersionUID = -1533010002030134172L;
	
	private String password;
	private String confirmedPassword;

	private User user;
	
	@Inject
	private ActivitiesManager activitiesManager;

	@Inject
	private IdentityManager identityManager;

	@Inject
	private RelationshipManager relationshipManager;

	@Inject
	private RepositoriesManager repositoriesManager;

	@Inject
	private HarvestersManager harvestersManager;

	@Inject
	private Identity identity;
	
	@Inject
	private DefaultLoginCredentials credentials;
	
	@PostConstruct
	public void init() {
		if (identity.isLoggedIn()) {
			user = (User) identity.getAccount();
		} else {
			user = new User();
		}
	}
	
	@Transactional
	public String register() {
		
		// check input
		// 1. username not exist
		// 2. password confirmed
		User check = BasicModel.getUser(identityManager, user.getLoginName());
		if (check != null) {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrNameExists", null);
			return "";
		}
		
		if (!password.equals(confirmedPassword)) {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrUserPwMismatch", null);
			return "";
		}
		
		identityManager.add(user);
		identityManager.updateCredential(user, new Password(password));

		Grant grant = new Grant(user, BasicModel.getRole(identityManager, "User"));
		relationshipManager.add(grant);

		activitiesManager.userCreated(user, null);
		
		credentials.setUserId(user.getLoginName());
		credentials.setPassword(password);
		identity.login();
		
		return "/user/dashboard?faces-redirect=true";
	}

	public String login() {
		AuthenticationResult result = identity.login();
		if (result == AuthenticationResult.SUCCESS) {
			return "dashboard?faces-redirect=true";			
		} else {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrUserAuthFail", null);
			return null;
		}
	}
	
	public String logout() {
		identity.logout();
		return "/public/home?faces-redirect=true";
	}

	// doesn't work, throws IdentityManagementException
	public String removeUser() {
		// don't delete account if repositories or harvesters are still attached
		if (repositoriesManager.countUserRepositories() > 0 || harvestersManager.countUserHarvesters() > 0) {
			AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrUserDeleteFail", null);
			return null;
		} else {
			String redirect = logout();
			identityManager.remove(user);
			return redirect;
		}
	}

	/**
	 * Builds the URL to request a profile picture from gravatar
	 * https://de.gravatar.com/
	 *
	 * @return A valid gravatar URL if a hash has been generated successfully and null otherwise
	 */
	public String getGravatarRequest() {
		String request = "https://www.gravatar.com/avatar/";

		if (getTrimmedAndHashedEmail() != null) {
			request += getTrimmedAndHashedEmail() + "?d=mm";
		} else {
			request += "?d=mm&f=y";
		}

		return request;
	}

	/**
	 * Trims and lowercases the currently logged in user's eMail and calculates an MD5 hash.
	 * This is required by the gravatar service for the fetching of profile pictures.
	 *
	 * @return 	MD5 hash of trimmed and lowercased email. Hash is also converted to lowercase
	 * 			Returns null in case an exception is thrown
	 */
	private String getTrimmedAndHashedEmail() {
		if (user.getEmail() == null) {
			return null;
		}

		String hashAsString = null;
		String preparedEmail = user.getEmail().trim().toLowerCase();

		try {

			// Calculate MD5 Hash
			MessageDigest md = MessageDigest.getInstance("MD5");
			md.update(preparedEmail.getBytes());
			byte hashedEmail[] = md.digest();

			// Convert MD5 byte stream to String representation
			StringBuilder sb = new StringBuilder();
			for (byte b : hashedEmail)
				sb.append(Integer.toHexString((b & 0xFF) | 0x100).substring(1,3));

			hashAsString = sb.toString().toLowerCase();

		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}

		return hashAsString;
	}

	@Transactional
	public void save() {
		if (password != null) {
			if (password.equals(confirmedPassword)) {
				identityManager.updateCredential(user, new Password(password));
			} else {
				AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrorPasswordChange", null);
			}
		}
		identityManager.update(user);
		// evaluate and apply new password if necessary
		AppLocalization.showMessage(FacesMessage.SEVERITY_INFO, "msgInfoUserUpdated", null);
	}

	public String getUsername() {
		return user.getLoginName();
	}

	public void setUsername(String username) {
		user.setLoginName(username);
	}

	public String getFirstName() {
		return user.getFirstName();
	}

	public void setFirstName(String firstName) {
		user.setFirstName(firstName);
	}

	public String getLastName() {
		return user.getLastName();
	}

	public void setLastName(String lastName) {
		user.setLastName(lastName);
	}

	public String getEmail() {
		return user.getEmail();
	}

	public void setEmail(String email) {
		user.setEmail(email);
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getConfirmedPassword() {
		return confirmedPassword;
	}

	public void setConfirmedPassword(String password) {
		this.confirmedPassword = password;
	}

}

src/main/java/de/fhg/fokus/odp/harvester/actions/UserController.java
package de.fhg.fokus.odp.harvester.actions;

import de.fhg.fokus.odp.harvester.application.AppLocalization;
import org.picketlink.idm.IdentityManager;
import org.picketlink.idm.RelationshipManager;
import org.picketlink.idm.model.basic.BasicModel;
import org.picketlink.idm.model.basic.Grant;
import org.picketlink.idm.model.basic.Role;
import org.picketlink.idm.model.basic.User;
import org.picketlink.idm.query.IdentityQuery;

import javax.faces.application.FacesMessage;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;
import java.io.Serializable;
import java.util.List;
import java.util.stream.Collectors;

@Named
@ViewScoped
public class UserController implements Serializable {

    @Inject
    private IdentityManager identityManager;

    @Inject
    private RelationshipManager relationshipManager;

    private List<User> users;

    private Role selectedRole;

    @Transactional
    public void load() {
        IdentityQuery<User> query = identityManager.getQueryBuilder().createIdentityQuery(User.class);
        users = query.getResultList();
    }

    public List<User> getUsers() {
        return users;
    }

    public List<Role> getRoles(User user) {
        List<Grant> grants = relationshipManager.createRelationshipQuery(Grant.class).setParameter(Grant.ASSIGNEE, user).getResultList();
        return grants.stream().map(Grant::getRole).collect(Collectors.toList());
    }

    public List<Role> getRoles() {
        List<Grant> grants = relationshipManager.createRelationshipQuery(Grant.class).getResultList();
        return grants.stream().map(Grant::getRole).collect(Collectors.toList());
    }

    @Transactional
    public void deleteUser(User user) {
        Role adminRole = BasicModel.getRole(identityManager, "Administrator");
        if (BasicModel.hasRole(relationshipManager, user, adminRole)) {
            List<Grant> grants = relationshipManager.createRelationshipQuery(Grant.class).setParameter(Grant.ROLE, adminRole).getResultList();
            if (grants.size() <= 1) {
                AppLocalization.showMessage(FacesMessage.SEVERITY_ERROR, "msgErrLastAdmin", null);
                return;
            }
        }
        identityManager.remove(user);
        IdentityQuery<User> query = identityManager.getQueryBuilder().createIdentityQuery(User.class);
        users = query.getResultList();
    }

    public Role getRole() {
        return selectedRole;
    }

    public void setRole(Role role) {
        selectedRole = role;
    }

}

src/main/webapp/protected/schedulings.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
<h:body role="document">
	<ui:composition template="../templates/main.xhtml">

		<ui:define name="metadata">
			<f:metadata>
				<f:viewParam name="offset" value="#{harvesterController.offset}" />
				<f:viewAction action="#{harvesterController.load}" />
			</f:metadata>
		</ui:define>

		<ui:define name="title">MTS - ${localized.schedulingsTitle}</ui:define>

		<ui:define name="content">

			<div class="page-header">
				<h1>
					${localized.schedulingsTitle} <span class="badge">${harvesterController.total}</span>
				</h1>
			</div>

			<h:form id="anyForm">
				<table class="table">
					<thead>
						<tr class="warning">
							<th>
								<h:commandLink styleClass="btn btn-xs btn-default" action="${harvesterController.sortAlphabetically()}">
									<i class="fa ${harvesterController.sort == 2  ? 'fa-sort-alpha-desc' : 'fa-sort-alpha-asc'}" />
									<f:ajax render="@form" />
								</h:commandLink>
							</th>
							<th />
							<th>
								<h:commandLink styleClass="btn btn-xs btn-default" action="${harvesterController.sortAlphabetically()}">
									<i class="fa ${harvesterController.sort == 2 ? 'fa-sort-amount-desc' : 'fa-sort-amount-asc'}" />
									<f:ajax render="@form" />
								</h:commandLink>
							</th>
							<th>
								<h:commandLink styleClass="btn btn-xs btn-default" action="${harvesterController.sortSchedule()}">
									<i class="fa ${harvesterController.sort == 4 ? 'fa-sort-numeric-desc' : 'fa-sort-numeric-asc'}" />
									<f:ajax render="@form" />
								</h:commandLink>
							</th>
							<th />
						</tr>
					</thead>
					<ui:repeat var="harvester" value="${harvesterController.allHarvesters}">
						<tr>
							<td>#{harvester.name}</td>
							<td>#{harvester.description}</td>
							<td>#{harvester.frequency.label}</td>
							<td>#{harvester.nextHarvestDate}</td>
							<td>
								<div class="pull-right">
									<h:link styleClass="text-warning" outcome="/user/editharvester?faces-redirect=true">
										<f:param name="id" value="#{harvester.id}" />
										<i class="fa fa-edit" aria-hidden="true" />
									</h:link>
								</div>
							</td>
						</tr>
					</ui:repeat>
				</table>
			</h:form>
			
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/protected/users.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
		xmlns:f="http://xmlns.jcp.org/jsf/core"
		xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
		xmlns:pf="http://primefaces.org/ui">
<h:body role="document">
	<ui:composition template="../templates/main.xhtml">

		<ui:define name="metadata">
			<f:metadata>
				<f:viewAction action="${userController.load}"/>
			</f:metadata>
		</ui:define>

		<ui:define name="title">MTS - ${localized.titleUserManagement}</ui:define>

		<ui:define name="content">
			<div class="page-header">
				<h1>
					<i class="fa fa-users" /> ${localized.titleUserManagement}
				</h1>
			</div>
			<div class="row">
				<div class="col-md-12">
					<h:form>
						<h:messages styleClass="list-unstyled"
									errorClass="alert alert-danger" infoClass="alert alert-success"
									warnClass="alert alert-warning" p:role="alert" />

							<div class="row">
								<div class="col-md-8">
									<ul class="list-group">
										<ui:repeat value="${userController.users}" var="user">
											<li class="list-group-item">
												<i class="fa fa-user" /> ${user.loginName}
												<h:commandLink action="${userController.deleteUser(user)}">
													<i class="fa fa-user-times" />
													<f:ajax render="@form" />
												</h:commandLink>
											</li>
										</ui:repeat>
									</ul>
								</div>
								<div class="col-md-4">
								</div>
							</div>
							<p/>
					</h:form>
				</div>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>